[build]
  publish = "."
  command = "echo 'No build step required for static files'"

# Redirect WebSocket connections to external signaling server
[[redirects]]
  from = "/ws/*"
  to = "wss://demos.yjs.dev/ws/:splat"
  status = 200
  force = true

# Serve index.html for all routes (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Enable WebSocket support for functions (if using Netlify Functions)
  # Note: This won't work for your current Node.js WebSocket server
  # You'll need to deploy the signaling server separately
